### PR TITLE
Allow empty tests for submission only usecases.

### PR DESCRIPTION
**Pull request by rainwoodman**
The use case for this patch to use ok-client to submit homework but not using okpy to perform any tests. It is still a well-formed `.ok` configuration even when there are no tests -- so ok-client shall not die when we do not perform tests on an empty set of tests.

The condition is used again later, when tests are 'resolved'. I think that shall be converted to a warning, but since we do not use any tests yet I cannot comment to much on that one.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Ideally we'd like to have this patch deployed to datahub before the semester starts such that we can avoid deploying dummy test files for phys-151. Thanks!

**Comment by rainwoodman** [comment]
@gunjanbaid @modichirag @ybh0822

**Comment by epai** [comment]
Hmm, I have a feeling that that was put in there for a reason, say so that tests aren't accidentally omitted when creating the `.ok` config file, and that this is desired behavior (as it's causing tests to break).

As a compromise, we could introduce some way to tell ok that tests were omitted on purpose, maybe by introducing a sentinel value for "tests":
```
{
"name": "hog"
...
"tests": None, <-- use "None" as the sentinel value
"protocols": [
...
}

**Comment by rainwoodman** [comment]
I see your points but I am not quite sure what exactly shall be done? (sounded quite trivial) I can take a further look but I wonder if it is more efficient if you just go ahead and make the changes?

**Comment by epai** [comment]
Yeah, I can do that!  Do you know if I have push access to your fork?

**Comment by Sumukh** [comment]
This is a good idea. Let's try and shepard this in.

**Comment by kavigupta** [comment]
This was resolved in a separate PR, so I'm closing this one.

**Pull request closed without merging**
